### ISSUE TITLE
Installation/Use on Python 3.12

### ISSUE THREAD

**Issue by LJNolan** [vrodgom/statmorph#10]
When creating an environment with Python 1.12 with photutils, statmorph, etc. as follows:

`conda create -n fabulovs-hst python=3.12 photutils=1.12 numpy scipy matplotlib ipython jupyter astropy nb_conda_kernels statmorph`

Conda successfully creates the environment with statmorph v0.3.3.  However, when using source_morphology, the following error is returned:

`File ~opt/anaconda3/envs/fabulovs-hst/lib/python3.12/site-packages/statmorph/statmorph.py:394 in __init__
if float(photutils.__version__) < 0.5:

ValueError: could not convert string to float: '1.13.0'`

Trying to force conda to install statmorph v0.5.7 with Python returns an error that v0.5.7 is only compatible with Python <3.11, which seems to be the intended behavior.  When I make a new environment as follows:

`conda create -n fabulovs-hst python=3.11 photutils numpy scipy matplotlib ipython jupyter astropy nb_conda_kernels statmorph=0.5.7`

the environment is created successfully, and I am able to use source_morphology without issue.  My guess of the problem is:

a) Statmorph v0.3.3 is listed (perhaps unintentionally) as compatible with Python 3.12, and
b) A version of photutils since the move to Python 3.12 changed how photutils.__version_ is returned to include subversions (the second decimal point) and thus the indicated line no longer functions as of 0.3.3, and thus in Python 3.12 writ large.

I am a relative Git novice, so please forgive any formatting issues.  My environment in 3.11 is working for my purposes, but figured this might be a useful issue to share.  Happy to provide any further information which would be helpful.

**Comment by vrodgom** [comment]
Hey, thanks for letting me know about this, and sorry for my slow reaction.

The absence of a Python 3.12 conda build was an omission on my part -- or rather, the result of confusion with some of the conda-forge tools that supposedly help to keep everything up-to-date (unsuccessfully, on this occasion, although it may have been my fault).

I was certainly not expecting conda to install the ancient statmorph v0.3.3 under any circumstance. This is the last version of statmorph with the "noarch" label, so that it supposedly works for any architecture, but it is so outdated that it is not useful anymore. I do not believe it is possible to delete these old builds from the conda database, so I will pay more attention to make sure that conda builds for new Python versions are actually being built successfully, in order to avoid statmorph v0.3.3 from being unintentionally installed again.

In any case, this issue should be fixed now. So, if you run your first command again, you should now end up with statmorph v0.5.7 and Python 3.12.
