### ISSUE TITLE
Discrepancy in the value for Clumpiness

### ISSUE THREAD

**Issue by bijusaha-astro** [vrodgom/statmorph#12]
I am currently working on a project to calculate the clumpiness factor for a set of galaxies. For this purpose, I am using the code [statmorph](https://arxiv.org/pdf/1809.08239), which calculates the CAS (concentration, asymmetry, and clumpiness) values for galaxies.

However, I have encountered some issues with the output values for clumpiness. Specifically, I am receiving negative and seemingly random values for the clumpiness (S) for many galaxies in my sample. To verify the accuracy of the output, I selected galaxy samples from [Conselice et al. (2003)](https://ui.adsabs.harvard.edu/abs/2003ApJS..147....1C/abstract), which have clumpiness values specified. After running the statmorph code on the set of galaxies from Conselice et al., I obtained different clumpiness values than those reported in the paper.

I have attached the code I used, as well as a list of the values I obtained compared with the values mentioned in Conselice et al. (2003). Could you please help me understand why there might be discrepancies in the values and how I can correct them?

The attachments are available in repository linked below:
https://github.com/bijusaha-astro/statmorphcode_trial

**Comment by vrodgom** [comment]
Hi, thanks for checking. I ran your notebook for one of the galaxies in your sample (NGC3079) and, as it turned out, the clumpiness value returned was not that of the main galaxy, but that of a foreground star. So, looking at your code, the issue can be traced back to the following line:

`morph = source_morphs[max_index]`

Here, `max_index` represents a label from the segmentation map (in this case 1, since 0 is always reserved for the background). However, `source_morphs` is just a list with entries corresponding to the labeled sources (excluding the background) from the segmap, so you cannot actually use the labels as indices. In this particular case, `max_index = 1`, but the entry of interest is actually `source_morphs[0]`. (I think `source_morphs[max_index - 1]` would work in general, but a more robust solution is described below.)

Perhaps the simplest solution here would be to call `SourceMorphology` directly (instead of `source_morphs`), passing the label of interest (`max_index`) as the third positional argument. This would also reduce computing time by _not_ running statmorph on all the sources in the image.

I acknowledge that I should add a more realistic example to the tutorial, i.e. how to handle image with many sources. But, for now, I hope this helps.

A couple more things to note:

1. The original definition of S by Conselice (2003) included a multiplicative factor of 10 (their eq. 2). However, this factor was dropped in Lotz et al. (2004), which is the definition I am using.

2. I suggest creating a "diagnostic image", as described at the end of the [tutorial](https://statmorph.readthedocs.io/en/latest/notebooks/tutorial.html#Examining-the-output), for every object you are looking at. This often helps to diagnose problems with the measurements (in this case, looking at the wrong object).
