### ISSUE TITLE
 How can I use my own Sky_mean value for the image?

### ISSUE THREAD

**Issue by oxno2** [vrodgom/statmorph#8]
Hello, I just want to use this code to calculate the Gini index and M20 for my image. I had got my own PSF, image, sigma maps and others. I obtained the sky mean from my own method, which is obtained via the 3-sigma clip from the cleaned sky image. However, this code use its own method to get the sky_mean. Thus, my results for the sersic index is much off from the Galfit. Is there any place for me to input my own sky mean and sky median?

**Comment by vrodgom** [comment]
Hi. Thanks for your interest. Since background subtraction is a nontrivial procedure, I decided to leave this up to the user. Therefore, the code expects an already background-subtracted image as input. This is specified in the documentation (https://statmorph.readthedocs.io/en/latest/description.html#input).

We decided to include sky_mean and sky_median as part of the output because some users might find them useful, but if you look into the source code, these values are not used in any of the calculations because the input image is already assumed to be background-subtracted.

Maybe you can try subtracting your own sky_mean or sky_median values from the input image before running statmorph?

I hope this helps.

**Comment by oxno2** [comment]
Thanks very much!
